<section id="slider" class="container-fluid">
    <div class="pagingInfo">&nbsp;</div>
    <div class="container slick-slider" data-mage-init='{"carousel": {"pagingInfoEnabled": true}}'>
        <div class="slide">
            <div class="slide-content">
                <div class="collection">collection 2020</div>
                <div class="new-arrivals">New Arrivals</div>
                <div class="discover"><a class="arrow-icon" href="#">Discover more items</a></div>
            </div>
        </div>
        <div class="slide">
            <div class="slide-content">
                <h4>Slide Title 2</h4>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et doloreLorem ipsum dolor sit amet, consetetur sadipscing elitr Lorem ipsum dolor sit amet, consetetur sadipscing elitr Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
        <div class="slide">
            <div class="slide-content">
                <h4>Slide Title 3</h4>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore Lorem ipsum dolor sit amet, consetetur sadipscing elitr Lorem ipsum dolor sit amet, consetetur sadipscing elitr Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</p>
            </div>
        </div>
    </div>
</section>
