<div class="custom_slider">
    <div class="own_slider_cont" data-mage-init='{"carousel":{"slickConfig": {"slidesToShow": 1, "dots": false, "slidesToScroll": 1, "vertical": false}}}'>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic1.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic2.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic3.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic4.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic5.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic6.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic7.jpg"}}" alt=""></div>
    <div class="own-slide"><img src="{{media url="wysiwyg/pic8_1.jpg"}}" alt=""></div>
</div>
</div>
