<div class="news">
    <p class="header-text">from fashion world</p>
    <div class="news-slider" data-mage-init='{"newsSlider":  "slidesToShow": 2,
                "slidesToScroll": 2,
                "dots": "true",
                "infinite": "true",
                "dotsClass": "my-dots",
                "responsive": [
                    {
                        "breakpoint": 600,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1,
                            "dots": "true"
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1,
                            "dots": "true"
                        }
                    },
                    {
                        "breakpoint": 300,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1,
                            "dots": "true"
                        }
                    }
                ]
            }}'>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
        <div class="slider-block">
            <div class="news-block">
                <div class="newsPic">&nbsp;</div>
                <div class="newsText">
                    <p class="newsDate">Posted 25 August</p>
                    <p class="secondHeader">Reveal the brand Shopping Strategy</p>
                    <p class="read-more"><a class="arrow-icon" href="#">read more</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
