<div class="featured-categories">
    <div class="categories-content">
        <div class="categories-block">
            <div class="categories-block-text">
                <div class="background-after">
                    <a class="arrow-icon" href="#">Summer shoes</a></div>
            </div>
        </div>
    </div>
    <div class="categories-content">
        <div class="categories-block">
            <div class="categories-block-text">
            <div class="categories-block-text2"><a class="arrow-icon" href="#">new trends</a></div>
            </div>
        </div>
    </div>
</div>
