,
"responsive": [
{
"breakpoint": 1130,
"settings": {
"slidesToScroll": 1,
"slidesToShow": 3
}
},
{
"breakpoint": 610,
"settings": {
"slidesToScroll": 1,
"slidesToShow": 2
}
},
{
"breakpoint": 600,
"settings": {
"slidesToShow": 2,
"slidesToScroll": 1
}
},
{
"breakpoint": 490,
"settings": {
"slidesToShow": 1,
"slidesToScroll": 1
}
},
{
"breakpoint": 220,
"settings": {
"slidesToShow": 1,
"slidesToScroll": 1
}
}
]
